apiVersion: v1
kind: Service
metadata:
  name: cabyssvc1
  labels:
    app: cabysapp1
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  selector:
    app: cabysapp1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cabysapp1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cabysapp1
    spec:
      containers:
      - name: cabysapp1
        image: lugua/cabysapp:v2.1
        ports:
        - containerPort: 9000